# Generated by Django 6.0.3 on 2026-03-13 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='姓名')),
                ('employee_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='工号')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('photo_path', models.CharField(blank=True, default='', max_length=255, verbose_name='照片路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '驾驶员',
                'verbose_name_plural': '驾驶员',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrivingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('risk', '危险驾驶'), ('fatigue', '疲劳驾驶'), ('distraction', '分心驾驶'), ('unknown', '未知')], default='risk', max_length=32, verbose_name='事件类型')),
                ('source_event_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='来源事件ID')),
                ('source_label', models.CharField(blank=True, default='', max_length=64, verbose_name='模型标签')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration_sec', models.FloatField(default=0.0, verbose_name='持续秒数')),
                ('peak_risk_conf', models.FloatField(default=0.0, verbose_name='峰值风险置信度')),
                ('trigger_frames', models.PositiveIntegerField(default=12, verbose_name='触发帧阈值')),
                ('recover_frames', models.PositiveIntegerField(default=10, verbose_name='恢复帧阈值')),
                ('snapshot_path', models.CharField(blank=True, default='', max_length=255, verbose_name='截图路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='monitoring.driver', verbose_name='驾驶员')),
            ],
            options={
                'verbose_name': '报警事件',
                'verbose_name_plural': '报警事件',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time'], name='monitoring__start_t_257cde_idx'), models.Index(fields=['event_type', '-start_time'], name='monitoring__event_t_641cc4_idx')],
            },
        ),
    ]
