# Generated by Django 6.0.3 on 2026-03-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_userprofile_rename_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingevent',
            name='snapshot_sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='截图哈希(SHA256)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id_card',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
