# Generated by Django 6.0.3 on 2026-03-22 07:20

from django.db import migrations, models


def normalize_event_types(apps, schema_editor):
    DrivingEvent = apps.get_model("monitoring", "DrivingEvent")
    DrivingEvent.objects.exclude(event_type="fatigue").update(event_type="fatigue")


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_drivingevent_snapshot_sha256_alter_driver_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='photo_path',
        ),
        migrations.RunPython(normalize_event_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='drivingevent',
            name='event_type',
            field=models.CharField(choices=[('fatigue', '疲劳驾驶')], default='fatigue', max_length=32, verbose_name='事件类型'),
        ),
    ]
