# Generated by Django 6.0.3 on 2026-03-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_driver_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '账号信息', 'verbose_name_plural': '账号信息'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('unknown', '未知'), ('male', '男'), ('female', '女')], default='unknown', max_length=16, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='手机号'),
        ),
    ]
