# Generated by Django 6.0.3 on 2026-03-22 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sync_profile_roles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("monitoring", "UserProfile")
    staff_ids = set(User.objects.filter(is_staff=True).values_list("id", flat=True))
    for profile in UserProfile.objects.all():
        role = "admin" if profile.user_id in staff_ids else "driver"
        if profile.role != role:
            profile.role = role
            profile.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_userprofile_options_userprofile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('driver', '驾驶员'), ('admin', '管理员')], default='driver', max_length=16, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='邀请码')),
                ('role', models.CharField(choices=[('admin', '管理员')], default='admin', max_length=16, verbose_name='用途角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='最大可用次数')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='备注')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(sync_profile_roles, migrations.RunPython.noop),
    ]
