# Generated by Django 6.0.3 on 2026-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_userprofile_role_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='邀请码'),
        ),
    ]
