# Generated by Django 6.0.3 on 2026-03-26 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_invitecode_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingevent',
            name='review_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='复核备注'),
        ),
        migrations.AddField(
            model_name='drivingevent',
            name='review_status',
            field=models.CharField(choices=[('pending', '待复核'), ('confirmed', '确认疲劳'), ('false_positive', '误报')], default='pending', max_length=20, verbose_name='复核状态'),
        ),
        migrations.AddField(
            model_name='drivingevent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复核时间'),
        ),
        migrations.AddField(
            model_name='drivingevent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_driving_events', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
    ]
