# Generated by Django 6.0.3 on 2026-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_drivingevent_review_note_drivingevent_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingevent',
            name='review_status',
            field=models.CharField(choices=[('auto', '系统判定'), ('pending', '待复核'), ('confirmed', '复核后确认疲劳'), ('false_positive', '复核后判定误报')], default='auto', max_length=20, verbose_name='复核状态'),
        ),
    ]
