# Generated by Django 6.0.3 on 2026-03-27 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_convert_legacy_pending_to_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_session_id', models.CharField(max_length=64, unique=True, verbose_name='来源会话ID')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_sec', models.FloatField(default=0.0, verbose_name='驾驶总时长(秒)')),
                ('source', models.CharField(blank=True, default='gui', max_length=32, verbose_name='来源')),
                ('status', models.CharField(choices=[('active', '进行中'), ('ended', '已结束')], default='active', max_length=12, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '驾驶会话',
                'verbose_name_plural': '驾驶会话',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='drivingevent',
            name='source_session_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='来源会话ID'),
        ),
        migrations.AddIndex(
            model_name='drivingevent',
            index=models.Index(fields=['source_session_id'], name='monitoring__source__694b5d_idx'),
        ),
        migrations.AddField(
            model_name='drivingsession',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_sessions', to=settings.AUTH_USER_MODEL, verbose_name='所属账号'),
        ),
        migrations.AddIndex(
            model_name='drivingsession',
            index=models.Index(fields=['-started_at'], name='monitoring__started_04a695_idx'),
        ),
        migrations.AddIndex(
            model_name='drivingsession',
            index=models.Index(fields=['status', '-started_at'], name='monitoring__status_e85d35_idx'),
        ),
    ]
